docs(contributing): Adding docs/developer.md page
openebs/dynamic-localpv-provisioner pull request #20
Opened 2021-01-05 07:13 UTC by niladrih

**Why is this PR required? What issue does it fix?**:
This PR adds the page docs/developer.md. This also fixes the dead link in the CONTRIBUTING.md page which links docs/developer.md

**What this PR does?**:
The developer.md page includes instructions for setting up the development environment.

~~**Does this PR require any upgrade changes?**:~~

~~**If the changes in this PR are manually verified, list down the scenarios covered:**:~~

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>

2021-01-06 05:30 UTC, akhilerm commented on docs/developer.md
> +* You have Go 1.10+ installed on your local host/development machine.
Go version that is used in the [build file](https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/buildscripts/provisioner-localpv/provisioner-localpv.Dockerfile#L15) should be used.

2021-01-06 05:31 UTC, akhilerm commented on docs/developer.md
> +* You have Docker installed on your local host/development machine. Docker is required for building maya component container images and to push them into a Kubernetes cluster for testing.
replace maya  components with localpv

2021-01-06 05:31 UTC, akhilerm commented on docs/developer.md
> + Checkout the master branch.
```suggestion
 Checkout the develop branch.
```

2021-01-06 05:32 UTC, akhilerm commented on docs/developer.md
> + Make sure you have the upstream remote openebs/maya by listing them.
replace maya with localpv repo name.

2021-01-06 05:32 UTC, akhilerm commented on docs/developer.md
> + Fetch all the changes from the upstream master branch.
```suggestion
 Fetch all the changes from the upstream develop branch.
```

2021-01-06 05:32 UTC, akhilerm commented on docs/developer.md
> + This command applies all the commits from the upstream master to your local master.
```suggestion
 This command applies all the commits from the upstream develop to your local develop.
```

2021-01-06 05:33 UTC, akhilerm commented on docs/developer.md
> + Push the rebased master to origin develop.
```suggestion
 Push the rebased develop to origin develop.
```

2021-01-06 05:34 UTC, akhilerm commented on docs/developer.md
> +This repo supports [Go Modules](https://github.com/golang/go/wiki/Modules), and
Instead of support,  we now use go modules only.

2021-01-06 05:35 UTC, akhilerm requested changes
Some changes are required regarding:
1. changing branch to develop from master
2. changing repo name in the docs.

2021-01-10 13:23 UTC, niladrih commented
Hi @akhilerm . I amended the previous commit and did a 'Resolve conversation' on the suggested changes. Also I re-requested a review from you. 

Let me know if any of this violates best practices.

2021-01-10 16:34 UTC, akhilerm commented
@niladrih instead of amending the commits and force pushing., you can just push as new commits. This will help to review only the changes done.  The rest is good.

2021-01-11 04:53 UTC, akhilerm approved these changes
LGTM

2021-01-12 05:53 UTC, kmova approved these changes

2021-01-12 05:53 UTC, merged